### ISSUE TITLE
Run Configuration

### ISSUE THREAD

**Issue by RahulDudharjiya** [seanaharrison/springmvc-mongodb-example#2]
Hi I know Its very late to ask but I am a beginner in java spring mvc So I Follow the exact step you wrote but at the end I can not runthe project.

No route is called. 

PageNotFound - No mapping found for HTTP request with URI [/springmvc-mongodb-example/] in DispatcherServlet with name 'dispatcherServlet'

This is the error

**Comment by seanaharrison** [comment]
Hey Rahul,

This project is very old, I recommend finding a newer example with Spring Boot.

https://spring.io/guides/gs/accessing-data-mongodb/

Regards,
Sean
